Repository bim-g/wepesi-metadata-generator, pull requests merged in 2023-03, with the labels that each got.

#17 Update README.md
  README.md
Labels: documentation

#18 add support for PHP8
  composer.json
  composer.lock
Labels: enhancement

#20 [FIX] keywords: method parameters defined for php 8
  example/index.php
  src/MetaData.php
Labels: bug

#22 [FIX] test: refactor project test.
  composer.json
  composer.lock
  src/MetaData.php
  test/MetaDataTest.php
Labels: bug
